#!/usr/bin/env python3
"""Regenerate INDEX.md from the SKILL.md files in skills/."""

import pathlib
import re
import sys
import yaml
from collections import defaultdict

def extract_metadata(content: str) -> dict:
    """Extract the <!-- metadata: ... --> block."""
    # Match both formats: <!-- metadata: ... --> and <!-- metadata:\n...-->
    match = re.search(r'<!-- metadata:\s*\n(.*?)-->', content, re.DOTALL)
    if not match:
        match = re.search(r'<!-- metadata:\s+(.*?)-->', content, re.DOTALL)
    if match:
        try:
            return yaml.safe_load(match.group(1)) or {}
        except yaml.YAMLError:
            return {}
    return {}

def extract_skill_info(skill_file: pathlib.Path, skills_dir: pathlib.Path) -> dict:
    """Extract info from a SKILL.md file."""
    content = skill_file.read_text()
    parts = content.split('---', 2)
    if len(parts) < 3:
        return {}

    try:
        fm = yaml.safe_load(parts[1])
    except yaml.YAMLError:
        return {}

    metadata = extract_metadata(content)

    # Get category from path: skills/<category>/<slug>/SKILL.md
    rel = skill_file.relative_to(skills_dir)
    path_category = rel.parts[0] if len(rel.parts) > 1 else ''

    return {
        'name': fm.get('name', ''),
        'description': fm.get('description', ''),
        'category': metadata.get('category', '') or path_category,
        'tags': metadata.get('tags', []),
        'difficulty': metadata.get('difficulty', ''),
        'path': str(rel),
    }

def main():
    skills_dir = pathlib.Path('skills')
    if not skills_dir.exists():
        print("Error: skills/ directory not found", file=sys.stderr)
        sys.exit(1)

    # Collect all skills
    skills_by_category = defaultdict(list)
    for skill_file in sorted(skills_dir.rglob('SKILL.md')):
        info = extract_skill_info(skill_file, skills_dir)
        if info:
            category = info.get('category', skill_file.parts[1])
            skills_by_category[category].append(info)

    # Build INDEX.md content
    total = sum(len(s) for s in skills_by_category.values())
    out = []
    out.append("# open-research-skills — Index\n")
    out.append(f"**{len(skills_by_category)} categories, {total} skills**\n")
    out.append("\nGenerated by `scripts/build-index.py` — do not edit by hand.\n")
    out.append("\n## Categories\n")
    out.append("| Category | Skills | Description |")
    out.append("|---|---|---|")

    # Sort categories by skill count desc
    sorted_cats = sorted(skills_by_category.items(), key=lambda x: -len(x[1]))

    descriptions = {
        'bioinformatics-sequence': 'FASTA/FASTQ/BAM/VCF, alignment, QC, Biopython',
        'chemoinformatics': 'RDKit, ADMET, virtual screening, retrosynthesis, generative design',
        'research-grants': 'NIH R01/K, NSF, ERC, fellowships, foundations, DARPA',
        'lab-automation': 'Opentrons/PyLabRobot, ELNs (eLabFTW/Chemotion/openBIS)',
        'career-navigation': 'Academic CV, tenure, industry transition, interview prep',
        'scientific-communication': 'Talks, posters, podcasts, press releases, elevator pitch',
        'open-science': 'FAIR data, preprints, preregistration, code release, licensing',
        'scientific-writing': 'Manuscript structure, cover letters, rebuttals, AI disclosure',
        'scientific-thinking': 'Brainstorming, critical thinking, hypothesis generation, perspective tour, failure handling',
        'scientific-visualization': 'Figure design, schematics, slides, posters, color & accessibility',
        'literature-research': 'Literature search, systematic review, citation management, paper lookup',
        'mentorship-teaching': 'Onboarding, goal setting, syllabus, course design',
        'image-analysis-microscopy': 'CellProfiler, QuPath, ImageJ/Fiji, best practices',
        'machine-learning-bio': 'Protein LMs, DL for genomics, AlphaFold, scRNA-seq DL',
        'ethics-compliance': 'IRB protocols, data privacy, AI disclosure, image integrity',
        'peer-review': 'Manuscript review, grant review, scholar evaluation, reviewer response',
        'humanizer-skills': 'Scientific voice, AI disclosure, text humanizing, AI detection awareness',
        'data-engineering': 'Snakemake pipeline management',
    }

    for category, skills in sorted_cats:
        desc = descriptions.get(category, '')
        out.append(f"| `{category}` | {len(skills)} | {desc} |")

    # Per-category detail
    out.append("\n## All skills\n")
    for category, skills in sorted_cats:
        out.append(f"\n### `{category}/` ({len(skills)} skills)\n")
        out.append("| Skill | Description | Difficulty |")
        out.append("|---|---|---|")
        for skill in sorted(skills, key=lambda s: s['name']):
            name = skill['name']
            desc = skill['description'].replace('|', '\\|')[:120]
            diff = skill.get('difficulty', '')
            out.append(f"| `{name}` | {desc} | {diff} |")

    # Write to INDEX.md
    pathlib.Path('INDEX.md').write_text('\n'.join(out) + '\n')
    print(f"Regenerated INDEX.md with {total} skills across {len(skills_by_category)} categories")

if __name__ == '__main__':
    main()